### ISSUE TITLE
RestClient::SSLCertificateNotVerified (SSL_connect returned=1 errno=0 state=error: certificate verify failed):

### ISSUE THREAD

**Issue by happybirds** [huacnlee/activestorage-aliyun#12]
本地上传没有问题
 上传到阿里云报错了

RestClient::SSLCertificateNotVerified (SSL_connect returned=1 errno=0 state=error: certificate verify failed):

**Comment by huacnlee** [comment]
搜索 Ruby SSL_connect returned=1 errno=0 state=error: certificate verify failed

这个是安装 OpenSSL 的问题
