### ISSUE TITLE
自定义域名如何配置？

### ISSUE THREAD

**Issue by beviz** [huacnlee/activestorage-aliyun#19]
README 中没有说明

**Comment by huacnlee** [comment]
你试试配置 `endpoint` 为自定义域名

**Comment by beviz** [comment]
尝试过的，如果域名为 `my.domain.com`，则得到的 URL 结构为 `bucket-name.my.domain.com`。难道不用填写 `bucket` ?

**Comment by huacnlee** [comment]
我来实际验证看看
在 2018年10月17日 +0800 14:36，bevis <notifications@github.com>，写道：

**Comment by huacnlee** [comment]
https://github.com/huacnlee/activestorage-aliyun#custom-domain

看这个说明
