### ISSUE TITLE
使用 Direct Upload 上传成功后，提交表单报签名错误

### ISSUE THREAD

**Issue by beviz** [huacnlee/activestorage-aliyun#20]
配置结构与 README 中相同，在 Direct Upload 上传成功后，使用 `signed_id` 提交表单，抛出 500 错误如下：

> Aliyun::OSS::ServerError (The request signature we calculated does not match the signature you provided. Check your key and signing method. RequestId: XXXXXX):

而实际数据也已经保存成功。

**Comment by huacnlee** [comment]
我验证没有问题，你可以看看 test/dummy 里面的用法

https://github.com/huacnlee/activestorage-aliyun/blob/master/test/dummy/app/views/users/_form.html.erb#L26

<img width="339" alt="2018-10-17 15 54 19" src="https://user-images.githubusercontent.com/5518/47070965-f2dc9c80-d224-11e8-9067-1463cd13148b.png">

**Comment by beviz** [comment]
抱歉，一直在忙别的事情。

我本地使用最简调用依然是 signature 不能通过验证，有没有可能是自定义域名之类导致的组合 sign 导致的不匹配呢？

**Comment by beviz** [comment]
又通过尝试不同配置发现，如果 `path` 设置为 `/`，就会出现 signature 错误了，改为其它字符，比如 `ooxx` 就不会报错了。

但 [README](https://github.com/huacnlee/activestorage-aliyun#usage) 里 写着默认为 `/`，请检查一下。

**Comment by huacnlee** [comment]
Just release 0.6.0 for fix this issue.
