### ISSUE TITLE
Can not override response header for an anonymous user

### ISSUE THREAD

**Issue by FrankFang** [huacnlee/activestorage-aliyun#37]
我调用 service_url 的到
```
https://jrgcdn1.oss-cn-beijing.aliyuncs.com/development/imvla2sv9m9bzch5n5uqj1o3d4mk?response-content-disposition=inline%3B+filename%3D%22hi%22%3B+filename%2A%3DUTF-8%27%27hi&response-content-type=image%2Fpng
```

然而用浏览器访问这个 url 会得到如下错误

![image](https://user-images.githubusercontent.com/839559/56884494-8d534d80-6a9c-11e9-8486-f45a32ebb1d7.png)

去掉查询参数反而不会有报错：

```
https://jrgcdn1.oss-cn-beijing.aliyuncs.com/development/imvla2sv9m9bzch5n5uqj1o3d4mk
```

得到图片内容。

难道我调用了 service_url 后要自行删掉查询参数？

不太理解，请指教。

**Comment by FrankFang** [comment]
这是阿里云给我的回复

> 工程师 69576 号 :    您好
抱歉，让您久等了。

您的访问形式有问题，OSS不支持。
正常访问形式：https://jrgcdn1.oss-cn-beijing.aliyuncs.com/development/nb8qeb3deupfdc5r3lva4mtsuomk

如果想设置文件的http头参数，参考附件1设置。
https://help.aliyun.com/document_detail/31913.html

**Comment by huacnlee** [comment]
`mode: public` 的吗？

**Comment by huacnlee** [comment]
Fixed in 0.6.4

**Comment by FrankFang** [comment]
@huacnlee Thanks. 打算什么时候发布一下？bundle install 没有找到 0.6.4

**Comment by FrankFang** [comment]
我的错，官方源有 0.6.4，ruby china 的源还没更新
