### ISSUE TITLE
如何获取临时授权 STS

### ISSUE THREAD

**Issue by quoyi** [huacnlee/activestorage-aliyun#68]
需要客户端通过 js 直传 OSS，内嵌 iframe 无法直接通过 `/rails/active_storage/direct_uploads` 上传，需要获取 STS 后再上传 OSS。

```ruby
# routes.rb
namespace :api do
  get :sts, to: 'oss#sts'
end

# controller.rb
def sts
  # new file parameters
  # params[:filename] => 'test.txt'   &&  params[:byte_size] =>  710221

  # old file information
  # ActiveStorage::Blob.find_by_filename(params[:filename])  => #<ActiveStorage::Blob id: 33, key: "phecdsvaqca2q0h4tacscis7r7wl", filename: "test.txt",  ... byte_size: 689744 ...>

  # Get direct upload signed url by `url_for_direct_upload` ?
end
```

**Comment by huacnlee** [comment]
https://guides.rubyonrails.org/active_storage_overview.html#direct-uploads

ActiveStorage 的 DirectUpload 功能无法满足？

**Comment by quoyi** [comment]
> https://guides.rubyonrails.org/active_storage_overview.html#direct-uploads
> 
> ActiveStorage 的 DirectUpload 功能无法满足？

是的，没办法直接使用。不过我已经通过 “override” direct_uploads action 绕过了 csrf、 session、headers 问题，手动创建 blob 对象直传后关联 signed_id ，具体步骤请移步 [Issues 32208](https://github.com/rails/rails/issues/32208#issuecomment-383737803) 感谢回复。
