### ISSUE TITLE
direct_upload在rails 6.1下有问题

### ISSUE THREAD

**Issue by clwy-cn** [huacnlee/activestorage-aliyun#70]
## 操作一

Rails 6.1中，对active storage，在模型中增加了service新的配置方法，例如：

```ruby
# models/user.rb

has_one_attached :avatar, service: :aliyun
```

development.rb中，未做修改，保持了默认

```rb
# config/environments/development.rb

config.active_storage.service = :local
```

非direct_upload文件时，可以正常上传到阿里云oss

```ruby
<%= form.file_field :avatar %>
```

使用direct_upload传文件时，依然上传到本地，而不是阿里云oss上。也就说模型中配置的service，根本没有生效。

```ruby
<%= form.file_field :avatar, direct_upload: true %>
```

chrome的netwok中，看不到请求阿里云oss的记录。

## 操作二

模型中，不配置service

```ruby
# models/user.rb

has_one_attached :avatar
```

development.rb中，修改为:aliyun

```rb
# config/environments/development.rb

config.active_storage.service = :aliyun
```

再次测试direct_upload文件，可以正确上传到阿里云oss了。
chrome的netwok中，也可以看到请求阿里云oss的记录。

## 结论：

初步判断，
- 在model中配置的service: :aliyun，在direct_upload方式下，完全没有生效。
- 非direct_upload方式下，可以正确的上传到阿里云oss

我不确定是Rails的问题，还是activestorage-aliyun的问题？

**Comment by huacnlee** [comment]
https://github.com/huacnlee/activestorage-aliyun/runs/1768874560

我在测试里面试了一下，没重现出来

**Comment by clwy-cn** [comment]
## 我尝试运行了你的代码

```
cd test/dummy
rails s
```

### 上传后，提示错误：

![image](https://user-images.githubusercontent.com/57120683/105873873-e74cc280-6036-11eb-822d-f12398a0192a.png)

### 检查阿里云oss
发现avatar上传成功，files的上传全部失败。

![image](https://user-images.githubusercontent.com/57120683/105874095-2c70f480-6037-11eb-9f3a-d97cf58f87fa.png)

### 检查了项目本身

发现tmp/storage目录下，出现了direct_upload上传的files文件。说明`has_many_attached :files, service: :aliyun`未生效，依然传到`:local`中了

![image](https://user-images.githubusercontent.com/57120683/105874295-6215dd80-6037-11eb-9fb8-770d8d46a7c9.png)

## 我还找到了Rails上关于这个问题的issue

https://github.com/rails/rails/pull/34935#issuecomment-598225230

https://github.com/rails/rails/pull/38957
